version: "3.9"
   
services:
  backend:
    image: anon811/tickets:backend
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
  frontend:
    image: anon811/tickets:frontend
    command: ["npm", "run", "start"]
    ports:
      - "9080:9080"
    

